# Generated by Django 4.1.3 on 2022-11-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=40)),
                ('endereco', models.CharField(max_length=50)),
                ('sexo', models.BooleanField(choices=[('F', 'Feminino'), ('M', 'Masculino')])),
                ('curso', models.CharField(choices=[('inf', 'Informática'), ('ali', 'Alimentos'), ('api', 'Apicultura')], max_length=3)),
            ],
        ),
    ]
